# The public documentation URL, used for sitemap.xml
url: "https://docs.telerik.com/teststudio"

## The application virtual path
baseurl: "/teststudio"

## The product name
productName: "Test Studio Documentation"

# Exclude files which should not be in the output
exclude: [README.md,Gemfile,Gemfile.lock,build.cmd,run.cmd,deploy.cmd,apireference/*, docs-watcher/*]

# CTA Panels
has_cta_panels: true

## Ignore API directory
navigation:
## Test Studio Documentation Main Nodes:
    index:
#    "introduction":
#        title: "Introduction"
#        position: 201
    "prerequisites":
        title: "Installation and Setup"
        position: 3
    "getting-started":
        title: "Getting Started" 
        position: 4
    "automated-tests":
        title: "Automated Tests with Test Studio"
        position: 5 
    "features":
        title: "Features"
        position: 6
    "advanced-topics":
        title: "Advanced Topics"
        position: 7
    "knowledge-base":
        title: "Knowledge Base"
        position: 8
    "troubleshooting-guide":
        title: "Troubleshooting Guide"
        position: 9
    "testing-framework":
        title: "Testing Framework"
        position: 10
    "test-studio-mobile":
        title: "Test Studio Mobile"
        position: 11

    "general-information":
       title: "General Information"
       position: 5
    "archived-docs":
       title: "Archive"
       position: 12

# === Installation and Setup ===
    prerequisites/installation:
        title: "Install Test Studio"
        position: 1
    prerequisites/license-activation:
        title: "Activate Test Studio License"
        position: 2
    prerequisites/configure-your-browser:
        title: "Configure Browsers for Test Automation"
        position: 3
    
# === General Information ===
    general-information/installation:
        title: "Installation"
        position: 1
    general-information/start-a-project:
        title: "Start a Project"
        position: 2
    general-information/configure-your-browser:
        title: "Configure your browser"
        position: 3
    general-information/create-test-standalone:
        title: "Create a Test (Standalone)"
        position: 4
    general-information/create-test-vsplugin:
        title: "Create a Test (VS plugin)"
        position: 5
    general-information/test-recording:
        title: "Test Recording"
        position: 6
    general-information/test-execution:
        title: "Test Execution"
        position: 7
    general-information/test-results:
        title: "Test Results"
        position: 8
    general-information/test-results/dashboard:
        title: "Executive Dashboard"
        position: 8

# === Automated Tests with Test Studio ===
    automated-tests/customize-project:
        title: "Customize Your Project"
        position: 1
    automated-tests/recording:
        title: "Record Tests in Test Studio"
        position: 2
    automated-tests/test-execution:
        title: "Execute Tests in Test Studio"
        position: 3
    automated-tests/test-results:
        title: "Analyze the Test Results"
        position: 4
    automated-tests/troubleshooting:
        title: "Troubleshoot a Failing Test"
        position: 5
    automated-tests/elements:
        title: "Elements in Test Studio"
        position: 6
    automated-tests/data-drive-test:
        title: "Data Driven Automated Tests"
        position: 7
    automated-tests/test-lists:
        title: "Test Lists in Test Studio"
        position: 8
    automated-tests/test-list-results:
        title: "Results from Test List Runs"
        position: 9
    automated-tests/scheduling:
        title: "Schedule Tests in Test Studio"
        position: 10
    automated-tests/scheduling-results:
        title: "Results from Scheduled Test Executions"
        position: 11
    automated-tests/responsive:
        title: "Web Responsive Tests in Test Studio"
        position: 12
    automated-tests/wpf:
        title: "WPF Tests in Test Studio"
        position: 13
    automated-tests/load:
        title: "Load Tests in Test Studio"
        position: 14
    automated-tests/performance:
        title: "Performance Tests in Test Studio"
        position: 15
    automated-tests/vs-plugin:
        title: "Test Studio Plugin for Visual Studio"
        position: 16
    automated-tests/coded-tests:
        title: "Implement Code in a Test"
        position: 17
    automated-tests/source-control:
        title: "Share a Test Studio Project in the Team"
        position: 18
    automated-tests/continuous-integration:
        title: "Implement Test Studio Tests in CI Builds"
        position: 19

# ....Customize Your Project
    "*built-in-help-tools":
        title: "Help Tools in Test Studio"
        position: 7

# === Scheduling Test Runs ===
    "*scheduling/multiple-machines-scheduling-setup":
        title: "Remote Scheduled Execution (Multiple Machines Setup)"
        position: 4
    "*scheduling/advanced-topics":
        title: "Scheduling Setup Advanced Topics"
        position: 11

# === Load Testing ===
    "*load/designing-load-tests":
        title: "Design Your Load Test"
        position: 1
    "*load/running-load-test":
        title: "Execute Load Test"
        position: 2
    "*load/load-testing-results":
        title: "Load Test Results"
        position: 3
    "*load/advanced-topics":
        title: "Advanced Topics for Load Test"
        position: 4
        
    "*source-control/git":
        title: "Git"
        position: 1
    "*source-control/tfs":
        title: "TFS"
        position: 2

# === Features ===
    features/data-driven-testing:
        title: "Data Driven Testing"
        position: 5
    features/scheduling-test-runs:
        title: "Scheduling Test Runs"
        position: 7
    features/test-maintenance:
        title: "Test Maintenance"
        position: 6
    features/recorder:
        title: "Recorder"
        position: 1
    features/recorder/advanced-recording-tools:
        title: "Advanced Recording Tools"
        position: 3
    features/recorder/advanced-recording-tools/element-steps:
        title: "Element Steps"
        position: 2
    features/recorder/advanced-recording-tools/element-steps/actions:
        title: "Actions"
        position: 2
    features/recorder/advanced-recording-tools/element-steps/verifications:
        title: "Verifications"
        position: 3
    features/recorder/mouse-actions:
        title: "Actions"
        position: 4
    features/recorder/verifications:
        title: "Verifications"
        position: 5
    features/elements-explorer:
        title: "Elements"
        position: 2
    features/project-settings:
        title: "Project Settings"
        position: 9
    features/dialogs-and-popups:
        title: "Dialogs & Popups"
        position: 4
    features/custom-steps:
        title: "Custom Steps from Step Builder"
        position: 8
    features/logical-steps:
        title: "Logical Steps"
        position: 11
    features/testing-types:
        title: "Testing Types"
        position: 3
    features/integration:
        title: "Integration"
        position: 12
    features/integration/bug-tracking:
        title: "Bug Tracking"
        position: 1
    features/integration/quality-center:
        title: "Quality Center"
        position: 2
    features/test-runners:
        title: "Test Runners"
        position: 14


    features/custom-layout:
        title: "Custom Layout"
        position: 15
    features/project-explorer:
        title: "Project Explorer"
        position: 17
    features/execute-apitest:
        title: "Execute API test as Step"
        position: 16
    features/coded-steps:
        title: "Coded Steps"
        position: 10
# ....Testing types
    "*performance-testing":
        title: "Performance Testing"
        position: 4
    "*load-testing":
        title: "Load Testing"
        position: 3
    "*manual-testing":
        title: "Manual Testing"
        position: 5
    "*exploratory-testing":
        title: "Exploratory Testing"
        position: 6

# === Scheduling Test Runs ===
    "*scheduling-test-runs/multiple-machines-scheduling-setup":
        title: "Remote Scheduled Execution (Multiple Machines Setup)"
        position: 4
    "*scheduling-test-runs/advanced-topics":
        title: "Scheduling Setup Advanced Topics"
        position: 11
        
# === Advanced Topics ===
    "*coded-steps":
        title: "Coded Steps"
    "*coded-samples":
        title: "Coded Samples"
#.....Coded Samples
    "*general":
        title: "General"
    "*html":
        title: "HTML"
    "*silverlight":
        title: "Silverlight"
    "*combobox-automation":
        title: "ComboBox Automation"
    "*radgridview-automation":
        title: "RadGridView Automation"
    "*wpf":
        title: "WPF"
#........................
    "*build-server":
        title: "Build Server"
# === Knowledge Base ===
    "*activation-kb":
        title: "Activation"
    "*best-practices-kb":
        title: "Best Practices"
    "*code-coverage-kb":
        title: "Code Coverage"
    "*data-driven-testing-kb":
        title: "Data Driven Testing"
    "*dialogs-and-popups-kb":
        title: "Dialogs and Popups"
    "*load-testing-kb":
        title: "Load Testing"
    "*project-configuration-kb":
        title: "Project Configuration"
    "*scheduling-kb":
        title: "Scheduling"
    "*silverlight-kb":
        title: "Silverlight"
    "*source-control-kb":
        title: "Source Control"
    "*test-automation-kb":
        title: "Test Automation"
    "*test-execution-kb":
        title: "Test Execution"
    "*test-recording-kb":
        title: "Test Recording"
    "*verification-kb":
        title: "Verification"
    "*visual-studio-kb":
        title: "Visual Studio"
    "*browsers-kb":
        title: "Browsers"
# === Troubleshooting Guide ===
    "*browser-inconsistencies-tg":
        title: "Browser Inconsistencies"
    "*cannot-launch-test-studio-tg":
        title: "Cannot Launch Test Studio"
    "*installation-problems-tg":
        title: "Installation Problems"
    "*load-testing-problems-tg":
        title: "Load Testing Problems"
    "*recording-problems-tg":
        title: "Recording Problems"
    "*scheduling-issues-tg":
        title: "Scheduling Issues"
    "*source-control-problems-tg":
        title: "Source Control Problems"
    "*test-execution-problems-tg":
        title: "Test Execution Problems"
    "*chrome-tg":
        title: "Chrome"
    "*firefox-tg":
        title: "Firefox"
    "*safari-tg":
        title: "Safari"
    "*silverlight-wpf-tg":
        title: "Silverlight WPF"
    "*test-maintenance-problems-tg":
        title: "Test Maintenance Problems"
    "*troubleshooting-tools-tg":
        title: "Troubleshooting Tools"
    "*verification-problems-tg":
        title: "Verification Problems"
    "*visual-studio-tg":
        title: "Visual Studio"
    "*network-related-problems-tg":
        title: "Network Related Problems"
# === Testing Framework ===
    "*write-tests-in-code":
        title: "Write Tests in Code"
    "*intermediate-topics-wtc":
        title: "Intermediate Topics"
        position: 1
    "*element-identification-wtc":
        title: "Element Identification"
    "*html-control-suite-wtc":
        title: "HTML Control Suite"
    "*settings-and-configuration-wtc":
        title: "Settings & Configuration"
    "*advanced-topics-wtc":
        title: "Advanced Topics"
        position: 2
    "*html-popups-and-dialogs-wtc":
        title: "WPF/HTML Dialogs and Popups"
    "*javascript-wtc":
        title: "Javascript"
    "*test-regions-wtc":
        title: "Test Regions"
    "*silverlight-wpf-automation-wtc":
        title: "Silverlight/WPF Automation"
    testing-framework/api-reference:
        title: "Api Reference"
# === Mobile Testing ===
    test-studio-mobile/getting-started:
       title: "Getting Started"
       position: 3
    test-studio-mobile/native-applications:
       title: "Native Applications"
       position: 4
    test-studio-mobile/native-applications/installation:
       title: "Installation"
       position: 1
    test-studio-mobile/native-applications/configure-your-app:
       title: "Configure Your App"
       position: 2
    test-studio-mobile/native-applications/connect-agent-app:
       title: "Connect Agent App"
       position: 3
    test-studio-mobile/web-applications:
       title: "Web Applications"
       position: 5
    test-studio-mobile/web-applications/configuration:
       title: "Configuration"
       position: 1
    test-studio-mobile/test-recording:
       title: "Test Recording"
       position: 6
    test-studio-mobile/test-recording/record-a-test:
       title: "Record a Test"
       position: 1
    test-studio-mobile/test-execution:
       title: "Test Execution"
       position: 7
    test-studio-mobile/features:
       title: "Features"
       position: 8
    test-studio-mobile/features/code-features:
       title: "Code Features"
       position: 1
    test-studio-mobile/knowledge-base:
       title: "Knowledge Base"
       position: 9
    test-studio-mobile/knowledge-base/continuous-integration:
       title: "Continuous Integration"
       position: 1
    test-studio-mobile/troubleshooting:
       title: "Troubleshooting Guide"
       position: 10
    test-studio-mobile/api-reference:
        title: "API Reference"
        position: 11

# === Archived Documentation ===
    archived-docs/recorder:
        title: "Test Recorder"
        position: 1

## Assign layout and category per different paths
defaults:
-
    scope:
        path: ""
    values:
        layout: "documentation"
        category: "default"
-
    scope:
        path: knowledge-base
    values:
        res_type: "kb"
- 
    scope:
        path: test-studio-mobile
    values:
        announcement: |
            Test Studio Mobile is in а process of discontinuation. Please refer to this <a href="https://www.telerik.com/blogs/test-studio-to-focus-on-web-testing?utm_medium=product&utm_source=documentation&utm_campaign=test-studio-blog-mobile-deprecation" target="_blank">page</a> for more information.

# Aliases available in the markdown template. The below will expand {{site.foo}} to Bar in the output
# "foo": "Bar"

product: "Progress Test Studio"
platform: teststudio
main_theme: teststudio
edit_repo_url: https://github.com/telerik/teststudio/edit/master/docs
tabbed_code_marker_length: 3
tabbed_code_complex_separator: true
api_reference_url: "api/"
download: https://www.telerik.com/download-trial-file/v2/test-studio-ultimate
nav:
  "Demos": https://www.telerik.com/teststudio/live-demos
  "Release History": https://www.telerik.com/support/whats-new/teststudio/release-history
  "About": https://www.telerik.com/teststudio
  "Pricing": https://www.telerik.com/purchase/teststudio

footer:
-
  title: "Getting Started"
  links:
    "Getting Started": https://www.youtube.com/playlist?list=PLvmaC-XMqeBadBenwSoANlrc57y4bGBVY
    "Videos": https://www.youtube.com/playlist?list=PLPd3ce5hn3ozSoFDKG4XElnE5nOQ6AyHd
    "Whats New": "https://www.telerik.com/support/whats-new/teststudio"
    "Roadmap": https://www.telerik.com/support/whats-new/teststudio/roadmap
-
  title: "Community"
  links:
    "Forums": https://www.telerik.com/forums/teststudio
    "Blogs": https://www.telerik.com/blogs/testing-alm
    "Feedback Portal": https://feedback.telerik.com/Project/161

footer_social: 
    facebook: https://www.facebook.com/Telerik/
    youtube: https://www.youtube.com/user/TelerikInc
    linkedin: https://www.linkedin.com/showcase/telerik/ 
    twitter: https://twitter.com/Telerik/ 

# Feedback Form Google Sheet ID		
ff-sheet-id: 33b86fb1-d8b0-c7b0-84c0-aaff59d0d84a 

# The google services configuration
google_tag_manager: GTM-6X92
gcs_engine: '001595215763381649090:ymztq4og6vc'
gcs_api_key: 'AIzaSyDLQ-eVOEEH8Godvt6PZq3vSMpI5dHhX54'


# Assets pipeline configuration
assets:
    cachebust: soft
    js_compressor: uglifier

## Do not edit below this line
safe: false
markdown: MarkdownProcessor
kramdown:
    toc_levels: 2..3
    smart_quotes: ["quot", "quot", "quot", "quot"]
    input: GFM
